title: HyeonYongLee's blog
author: HyeonYongLee
email: HyeonYongLee.dev@gmail.com
copyright: © 2019 GitHub User
description: > # this means to ignore newlines until "show_excerpts:"
  Hi this is my first git blog

show_excerpts: false # set to true to show excerpts on the homepage

lin:
  date_format: "%b %-d, %Y"

  # path to the author avatar image
  avatar_path: assets/images/avatar.jpg

  # generate social links
  social_links:
    github:  "HyeonYongLee.github.io"
    linkedin: "HYEONYONG LEE"
theme: lin

plugins:
 - jekyll-feed
 - jekyll-seo-tag
